# Generated by Django 3.2.9 on 2021-11-17 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_produto_quantidade'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produto',
            new_name='Produtos',
        ),
    ]
